version: '3'

services:
  proxy:
    build: ./src
    command: bash -c "./run.sh"
    volumes:
      - /var/log/erss:/var/log/erss:rw
    image: hwk2-sq44_proxy:latest
    ports:
      - "12345:12345"
    tty: true